# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-04 14:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=50)),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='happen_event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ManageModel.Event')),
            ],
        ),
        migrations.CreateModel(
            name='have_task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='in_team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='involve_project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=50)),
                ('birth', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=50)),
                ('deadline', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=50)),
                ('leader_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ManageModel.Person')),
            ],
        ),
        migrations.AddField(
            model_name='involve_project',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ManageModel.Project'),
        ),
        migrations.AddField(
            model_name='involve_project',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ManageModel.Team'),
        ),
        migrations.AddField(
            model_name='in_team',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ManageModel.Person'),
        ),
        migrations.AddField(
            model_name='in_team',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ManageModel.Team'),
        ),
        migrations.AddField(
            model_name='have_task',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ManageModel.Person'),
        ),
        migrations.AddField(
            model_name='have_task',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ManageModel.Task'),
        ),
        migrations.AddField(
            model_name='happen_event',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ManageModel.Team'),
        ),
    ]
