# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 06:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManageModel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='detail',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AddField(
            model_name='task',
            name='detail',
            field=models.CharField(default='null', max_length=200),
        ),
    ]
