# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-11 07:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ManageModel', '0002_auto_20161207_0631'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='leader_id',
            new_name='leader',
        ),
    ]
