# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-11 08:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ManageModel', '0003_auto_20161211_0756'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='in_team',
            unique_together=set([('person', 'team')]),
        ),
    ]
