# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-11 09:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ManageModel', '0004_auto_20161211_0856'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='happen_event',
            unique_together=set([('team', 'event')]),
        ),
        migrations.AlterUniqueTogether(
            name='have_task',
            unique_together=set([('person', 'task')]),
        ),
        migrations.AlterUniqueTogether(
            name='involve_project',
            unique_together=set([('project', 'team')]),
        ),
    ]
