# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-18 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManageModel', '0005_auto_20161211_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='detail',
            field=models.CharField(default='null', max_length=200),
        ),
    ]
